ugly fix for bad performance due exaustion of pregens at big servers
taikedz-mt/rspawn pull request #7
Opened 2021-10-21 01:52 UTC by mckaygerhard

* if spawnrand_exists then delegate randomized spawn point to that mod if exits
* added `rspawn.random_delegate_use` - also by setting to delegate or not to psawnrand mod
* added optional depends to my fork of https://github.com/NathanSalapat/random_spawn
* the spawnrand can be found at https://codeberg.org/minenux/spawnrand
* also close https://github.com/taikedz-mt/rspawn/issues/6
* documented the changes in the settings types and README files

2021-10-21 12:04 UTC, taikedz requested changes
Adding optional support for an external mod is not a bad idea actually, and if it works, then great.

However, there are other features to rspawn around towns and guestlists, and those will not work with this change - the protections etc need to lookup player spawnpoints in the rspawn specific table. There are also other functions which dip into that table to look for the player's custom spawn - anywhere `rspawn:playerspans` is invoked with a playername.

You would have to update those to appropriately return the spawnpoint of the player from the alternative spawn mod, otherwise this change would actually break the mod (and crash the server if a player tries to use the town facilities).

2021-10-21 12:04 UTC, taikedz commented on init.lua
> +if spawnrand_exists == false and rspawn.random_delegate_use == "false" then
This should be an `or`:

If `spawnrand_exists` is actually true, but `delegate_use` is `false` then we should still use rspawn (the user may have wanted to turn it off for some reason temporarily)

2021-10-21 12:04 UTC, taikedz commented on init.lua
> +
You've added an `if` block, please indent the block that is under it

2021-10-21 12:04 UTC, taikedz commented on init.lua
> +    minetest.log("warning", "rspawn -- loaded but randown spawn for new players are from spawnrand ")
Should be "info" - warning is when something went wrong but not fatally, which is not the case here 😄

2021-10-21 18:49 UTC, mckaygerhard commented on init.lua
> +if spawnrand_exists == false and rspawn.random_delegate_use == "false" then
yes cos was marked to do not delegate (false) ,

2021-10-21 18:49 UTC, mckaygerhard commented on init.lua
> +
i tried but it generates and error with the minetes.fucntions i dont know why so that's why is not idented..

2021-10-21 18:50 UTC, mckaygerhard commented on init.lua
> +    minetest.log("warning", "rspawn -- loaded but randown spawn for new players are from spawnrand ")
umm intersting.. i see this as a fatal advertise to the admin.. ok got it but i will change after you review my response about delegation in main comment

2021-10-21 19:06 UTC, mckaygerhard commented
> Adding optional support for an external mod is not a bad idea actually, and if it works, then great.

the suggested used is my fork of `random_spawn` but as i said.. the `random_spawn` itseft is an api .. so after this firs "ugly hack" the process is to change gradually, see the comments: 

> However, there are other features to rspawn around towns and guestlists,....

yes my change only provide usage for beds and normal ones.. that the next to do if we must delegate the logic of spawn point exaustion:

1. in the random_spawn there's ony two functions: `find_ground(pos, player)` and `spawnrand(player)`
2. the first is the need to sustitute your `rspawn:genpos()` i guess
3. the second one is the "almost" sustitute of `rspawn:newspawn` 
4. and.. but will need the parto of protected areas in last one

that's why i set the config option "delegate" so it delegates all the logic only and mark the merge request as ugly fix.. 

i will provide another one @taikedz  this time for a fix over your line: `minetest.find_nodes_in_area(pos1, pos2, ` cos you used force loading and memory crash due max loding of memory

2021-10-22 11:27 UTC, taikedz commented on init.lua
> +if spawnrand_exists == false and rspawn.random_delegate_use == "false" then
When `spawnrand_exists` is not equal to `false`, the expression here evaluates overall to `false`, and jumps to using `spawn_rand` - even if the setting specifically says to not delegate (`rspawn.random_delegate_use == "false"` evaluatues `true`).

This needs to be `or` to honour the setting.

2021-10-22 11:28 UTC, taikedz commented on init.lua
> +
I'll have a go at it when I have a moment - this shouldn't generate an error on indent 🤔

2021-10-22 11:30 UTC, taikedz commented
@mckaygerhard - I understand that you would want to add support for other things separately, but if we merge this as it is, the mod will be in a bad state in `master` and break server for anyone who cloned it after merge and used the .

BTW Your change prevents player spawns registering in `rspawn`, but does not switch off the spawn pre-gen globalstep which is the thing that really is eating up resources. So even with your change, the forceload on globalstep is still happening 😨

So this cannot go in without the appropriate fixes unfortunately.

2021-10-22 12:44 UTC, mckaygerhard commented on init.lua
> +if spawnrand_exists == false and rspawn.random_delegate_use == "false" then
ok ok got it.. tested and you have right..  i dont know why it working in server.. i 'll check why works in my side .. there's something i missed then..

2021-10-22 12:46 UTC, mckaygerhard commented
> @mckaygerhard - I understand that you would want to add support for other things separately, but if we merge this as it is, the mod will be in a bad state in `master` and break server for anyone who cloned it after merge and used the .
>  ....
> So this cannot go in without the appropriate fixes unfortunately.

umm understood .. so i try to improved this and found a way to improved.. i'll close the merge and redone the work @taikedz  i'll be back with better aproach

2021-10-22 12:46 UTC, closed without merging